import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Printer, Download, Filter, FileText } from 'lucide-react';
import api from '../../lib/api';

const REPORT_TYPES = [
  { id: 'project-summary', name: 'Project Summary Report' },
  { id: 'monthly-progress', name: 'Monthly Progress Report' },
  { id: 'cost-budget', name: 'Cost & Budget Report' },
  { id: 'boq', name: 'BOQ & Estimation Report' },
  { id: 'procurement', name: 'Procurement Report' },
  { id: 'risk', name: 'Risk & Issue Report' },
  { id: 'labour', name: 'Labour & Attendance Report' },
  { id: 'dpr', name: 'Daily Progress (DPR) Report' },
];

export function ReportsPage() {
  const [selectedType, setSelectedType] = useState(REPORT_TYPES[0].id);
  const [projectId, setProjectId] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  // Fetch projects for the filter dropdown
  const { data: projects } = useQuery({
    queryKey: ['projectsForReports'],
    queryFn: async () => {
      const res = await api.get('/projects');
      return res.data;
    }
  });

  const { data: reportData, isLoading, refetch } = useQuery({
    queryKey: ['report', selectedType, projectId],
    queryFn: async () => {
      let url = `/reports/${selectedType}`;
      if (projectId) url += `?projectId=${projectId}`;
      const res = await api.get(url);
      return res.data;
    },
    enabled: false // Don't fetch automatically until they click "Generate"
  });

  const handleGenerate = () => {
    setIsGenerating(true);
    refetch().finally(() => setIsGenerating(false));
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 print:hidden">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Executive Reports</h1>
          <p className="text-sm text-slate-500 mt-1">Generate and print high-level project reports.</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={handlePrint}
            disabled={!reportData}
            className="px-4 py-2 bg-white border border-slate-200 rounded-md text-sm font-medium text-slate-700 hover:bg-slate-50 shadow-sm transition-colors flex items-center gap-2 disabled:opacity-50"
          >
            <Printer size={16} /> Print Report
          </button>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 print:hidden">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-end">
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Report Type</label>
            <select 
              value={selectedType}
              onChange={(e) => setSelectedType(e.target.value)}
              className="w-full rounded-md border-slate-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 p-2 border"
            >
              {REPORT_TYPES.map(type => (
                <option key={type.id} value={type.id}>{type.name}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Filter by Project (Optional)</label>
            <select 
              value={projectId}
              onChange={(e) => setProjectId(e.target.value)}
              className="w-full rounded-md border-slate-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 p-2 border"
            >
              <option value="">All Projects (Portfolio)</option>
              {projects?.map((p: any) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
          </div>
          <div>
            <button 
              onClick={handleGenerate}
              className="w-full md:w-auto px-6 py-2 bg-blue-600 border border-transparent rounded-md text-sm font-medium text-white hover:bg-blue-700 shadow-sm transition-colors"
            >
              {isGenerating || isLoading ? 'Generating...' : 'Generate Report'}
            </button>
          </div>
        </div>
      </div>

      {/* Report Preview / Print Area */}
      {reportData && (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-8 print:border-none print:shadow-none print:p-0">
          <div className="border-b border-slate-200 pb-6 mb-6">
            <h2 className="text-2xl font-bold text-slate-900">{REPORT_TYPES.find(r => r.id === selectedType)?.name}</h2>
            <div className="flex justify-between items-center mt-2 text-sm text-slate-500">
              <span>Generated on: {new Date(reportData.generatedAt).toLocaleString()}</span>
              <span>Generated by: {reportData.generatedBy}</span>
            </div>
            {projectId && (
              <div className="mt-2 text-sm font-medium text-blue-700 bg-blue-50 px-3 py-1 rounded inline-block">
                Project Filter: {projects?.find((p: any) => p.id === projectId)?.name}
              </div>
            )}
          </div>

          <div className="space-y-8">
            {selectedType === 'project-summary' && (
              <div>
                {reportData.projects?.length === 0 ? (
                  <p className="text-slate-500 italic">No project data available.</p>
                ) : (
                  <table className="min-w-full divide-y divide-slate-200">
                    <thead className="bg-slate-50">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Project Name</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Status</th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Contract Value</th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Progress</th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Open Issues</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-slate-200">
                      {reportData.projects?.map((p: any) => (
                        <tr key={p.id}>
                          <td className="px-4 py-3 text-sm font-medium text-slate-900">{p.name}</td>
                          <td className="px-4 py-3 text-sm text-slate-500">{p.status}</td>
                          <td className="px-4 py-3 text-sm text-slate-900 text-right">₹{p.contractValue?.toLocaleString()}</td>
                          <td className="px-4 py-3 text-sm text-slate-900 text-right">{p.progress}%</td>
                          <td className="px-4 py-3 text-sm text-red-600 font-medium text-right">{p.openIssues}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>
            )}
            
            {selectedType === 'cost-budget' && (
              <div>
                <table className="min-w-full divide-y divide-slate-200">
                  <thead className="bg-slate-50">
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Project Name</th>
                      <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Budget</th>
                      <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Actual Cost</th>
                      <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Committed Cost</th>
                      <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Variance</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-slate-200">
                    {reportData.financials?.map((p: any) => (
                      <tr key={p.id}>
                        <td className="px-4 py-3 text-sm font-medium text-slate-900">{p.name}</td>
                        <td className="px-4 py-3 text-sm text-slate-900 text-right">₹{p.budget?.toLocaleString()}</td>
                        <td className="px-4 py-3 text-sm text-amber-700 text-right">₹{p.actualCost?.toLocaleString()}</td>
                        <td className="px-4 py-3 text-sm text-blue-700 text-right">₹{p.committedCost?.toLocaleString()}</td>
                        <td className={`px-4 py-3 text-sm font-medium text-right ${p.variance < 0 ? 'text-red-600' : 'text-emerald-600'}`}>
                          ₹{p.variance?.toLocaleString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {selectedType === 'risk' && (
              <div>
                <table className="min-w-full divide-y divide-slate-200">
                  <thead className="bg-slate-50">
                    <tr>
                      <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Code</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Project</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Title</th>
                      <th className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Category</th>
                      <th className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Score</th>
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-slate-200">
                    {reportData.risks?.map((r: any) => (
                      <tr key={r.id}>
                        <td className="px-4 py-3 text-sm text-slate-500">{r.riskCode}</td>
                        <td className="px-4 py-3 text-sm text-slate-900">{r.project?.name}</td>
                        <td className="px-4 py-3 text-sm font-medium text-slate-900">{r.title}</td>
                        <td className="px-4 py-3 text-sm text-slate-500">{r.category}</td>
                        <td className="px-4 py-3 text-sm font-bold text-slate-900 text-right">{r.riskScore}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
            
            {['monthly-progress', 'boq', 'procurement', 'labour', 'dpr'].includes(selectedType) && (
              <div className="text-center py-10 bg-slate-50 rounded-lg">
                <FileText className="mx-auto text-slate-400 mb-3" size={32} />
                <h3 className="text-lg font-medium text-slate-800">Raw Data Format</h3>
                <p className="text-sm text-slate-500 mt-1">This report generates structured JSON data ready for external reporting tools or custom templates.</p>
                <div className="mt-6 text-left max-w-4xl mx-auto bg-slate-900 rounded overflow-hidden">
                  <pre className="p-4 text-emerald-400 text-xs overflow-x-auto whitespace-pre-wrap">
                    {JSON.stringify(reportData, null, 2)}
                  </pre>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
